### ISSUE TITLE
Fix errors in integration tests on shutdown of client

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-grpc#47]
I see some stack traces in tests sometimes because a context is closed before the client is shutdown. Not sure why, and it's mostly harmless, but it would be good to not see it.

**Comment by CyberZujo** [comment]
@dsyer Can I take this one?

**Comment by dsyer** [comment]
Sure. I don’t really know how to start. As far as I know we already shut the clients down. It might just be a test that needs fixing?

**Comment by dsyer** [comment]
It's a duplicate of #12

**Comment by dsyer** [comment]
Example:

```
2025-01-22T12:03:02.073Z  INFO 2101293 --- [grpc-server] [ault-executor-0] o.s.grpc.sample.GrpcServerService        : Hello foo
2025-01-22T12:03:02.075Z ERROR 2101293 --- [grpc-server] [ault-executor-0] io.grpc.internal.SerializingExecutor     : Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@25f6f7aa

java.lang.IllegalStateException: call already closed	at com.google.common.base.Preconditions.checkState(Preconditions.java:513) ~[guava-33.3.1-jre.jar:na]
Preconditions.java:513
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:218) ~[grpc-core-1.69.0.jar:1.69.0]
ServerCallImpl.java:218
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:213) ~[grpc-core-1.69.0.jar:1.69.0]
ServerCallImpl.java:213
	at org.springframework.grpc.server.exception.GrpcExceptionHandlerInterceptor$ExceptionHandlerListener.onHalfClose(GrpcExceptionHandlerInterceptor.java:108) ~[classes/:na]
GrpcExceptionHandlerInterceptor.java:108
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:356) ~[grpc-core-1.69.0.jar:1.69.0]
ServerCallImpl.java:356
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861) ~[grpc-core-1.69.0.jar:1.69.0]
ServerImpl.java:861
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.69.0.jar:1.69.0]
ContextRunnable.java:37
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.69.0.jar:1.69.0]
SerializingExecutor.java:133
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
ThreadPoolExecutor.java:1136
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
ThreadPoolExecutor.java:635
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Thread.java:833

2025-01-22T12:03:02.155Z  INFO 2101293 --- [grpc-server] [ionShutdownHook] o.s.g.s.lifecycle.GrpcServerLifecycle    : Completed gRPC server shutdown
```

**Comment by aabdurashidov** [comment]
@dsyer Hi. thanks for your work.

Just created an [issue](https://github.com/spring-projects-experimental/spring-grpc/issues/107) and just have seen this issue. can this one be main reason why exception handler is not working?

**Comment by dsyer** [comment]
We fixed the first example above (I think) with 7389498. The second one is probably still possible.

**Comment by aabdurashidov** [comment]
Thanks for your effort.
